@TodoMiniAPI_HostAddress = http://localhost:5000

GET {{TodoMiniAPI_HostAddress}}/todoitems/
Accept: application/json

###Replace {id}
GET {{TodoMiniAPI_HostAddress}}/todoitems/{id}
Accept: application/json

###
POST {{TodoMiniAPI_HostAddress}}/todoitems/
Content-Type: application/json

{
    "Title": "Study Czech",
    "Description": "1. Podstatná jména 2. Přídavná jména",
    "IsComplete": false
}

###Replace {id}
PUT {{TodoMiniAPI_HostAddress}}/todoitems/{id}
Content-Type: application/json

{
    "Name": "Study Czech",
    "IsComplete": true
}

###Replace {id}
DELETE {{TodoMiniAPI_HostAddress}}/todoitems/{id}
